version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - ARTIFACTS_DIR=/app/artifacts
      - LOG_DIR=/app/logs
    volumes:
      - ./artifacts:/app/artifacts
      - ./logs:/app/logs
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    environment:
      - DIAGNOSIS_API_URL=http://localhost:8000
    ports:
      - "8501:8501"
    depends_on:
      - api
